feat(linter): Add jsx-a11y/alt-text
oxc-project/oxc pull request #1126
Opened 2023-11-01 03:36 UTC by manzt

Had to comment out a couple of tests with TODOs related to evaluating logical expressions and polymorphic components, but I think these are largely edge cases for detecting validity of alt text. The most important cases are covered.

2023-11-01 06:18 UTC, Boshen commented
Let's ignore the perf regression. There are no jsx in the files being benchmarked, there's probably something else going on.

2023-11-01 11:01 UTC, mysteryven requested changes

2023-11-02 17:07 UTC, manzt commented on crates/oxc_linter/src/rules/jsx_a11y/alt_text.rs
> +    correctness
Correctness, by definition provided, relates to "code that is outright wrong or useless." This definition is of course subjective, but in my personal view, "outright wrong or useless" can be broadened to include code that fails to be accessible. 

Missing alt text on visual elements poses a significant issue for visually impaired users. Screen readers rely on alt text to narrate the content of images, making web content accessible. A site without alt text doesn't just lack in style or has a code written in a less idiomatic way—it's essentially excluding a subset of users – I'd argue "outright wrong" from an accessibility standpoint.

While missing alt text could be `suspicious` (possibly an oversight), this category might be too mild given the importance of web accessibility. Definitely up for discussion for many of the `eslint-plugin-jsx-a11y` rules, but perhaps a more clear description of `correctness` is needed.

2023-11-02 17:09 UTC, manzt commented on crates/oxc_linter/src/rules/jsx_a11y/alt_text.rs
> +    correctness
Another option would be to add a category explicitly for accessibility.

2023-11-03 01:01 UTC, mysteryven commented on crates/oxc_linter/src/rules/jsx_a11y/alt_text.rs
> +    correctness
I agree with you, and I met a similar issue when writing Jest rules. How can we solve it? @Boshen

2023-11-03 02:58 UTC, Boshen commented on crates/oxc_linter/src/rules/jsx_a11y/alt_text.rs
> +    correctness
We currently have a `--import-plugin` option for turning on import plugins, let's also add `--jsx-a11y-plugin` and `--jest-plugin` flags for turning on these rules.

2023-11-03 02:59 UTC, Boshen commented on crates/oxc_linter/src/rules/jsx_a11y/alt_text.rs
> +    correctness
https://github.com/web-infra-dev/oxc/issues/1138

2023-11-03 03:01 UTC, Boshen approved these changes
Awesome work! I didn't expect that this rule could be so complicated.

2023-11-03 03:02 UTC, merged