feat(linter): implement `eslint(constructor-super)`
oxc-project/oxc pull request #126
Opened 2023-03-05 05:44 UTC by shannonrothe

2023-03-05 06:01 UTC, shannonrothe commented on crates/oxc_linter/src/rules/constructor_super.rs
> +            Self::StringLiteral(lit) => Some(lit.span),
There are more things to handle that are considered a "non-constructor" but I haven't yet covered them all

2023-03-06 15:32 UTC, Boshen requested changes
Need to rebase and add nursery.

2023-03-07 09:12 UTC, shannonrothe commented
> Need to rebase and add nursery.

Done 👍🏼

2023-03-07 10:22 UTC, Boshen approved these changes

2023-03-07 10:22 UTC, merged