feat(linter) deepscan: bad object literal comparison
oxc-project/oxc pull request #1844
Opened 2023-12-27 20:20 UTC by camc314

2023-12-27 20:20 UTC, camc314 commented
Current dependencies on/for this PR:
* `main`
  * **PR #1844** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/1844?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/1844?utm_source=stack-comment).

2023-12-28 01:30 UTC, Dunqing requested changes, later dismissed

2023-12-28 01:30 UTC, Dunqing commented on crates/oxc_linter/src/rules/deepscan/bad_object_literal_comparison.rs
> +    ///x
```suggestion
    ///
```

2023-12-28 13:53 UTC, Boshen approved these changes

2023-12-28 13:54 UTC, merged