feat(linter): no irregular whitespace
oxc-project/oxc pull request #1877
Opened 2024-01-02 18:55 UTC by DeividAlmeida

it was builded a loop that iterates in trivias.irregular-whitespace and return the warning if contain some specific sequence of chars.

2024-01-02 20:08 UTC, DeividAlmeida commented
Do you have any suggestion to improve the performance?

2024-01-02 20:08 UTC, DeividAlmeida commented
do you have any suggestion to improve the performance?

2024-01-03 03:13 UTC, Dunqing requested changes
I don't think we need to check irregular_whitespaces again. we can loop over irregular_whitespaces and just call ctx.diagnostic(NoIrregularWhitespaceDiagnostic(irregular_ whitespace)) and that's it!

2024-01-03 03:13 UTC, Dunqing commented on crates/oxc_linter/src/rules/eslint/no_irregular_whitespace.rs
> +                .unwrap();
```suggestion
            let char = irregular_whitespace.source_text(ctx.source_text())
```

2024-01-03 03:47 UTC, Boshen commented on crates/oxc_linter/src/rules/eslint/no_irregular_whitespace.rs
> +        let irregular_whitespaces = ctx.semantic().trivias().irregular_whitespaces().to_owned();
`to_owned` is a clone here I think, which is unecessary.

2024-01-03 11:25 UTC, DeividAlmeida commented
> I don't think we need to check irregular_whitespaces again. we can loop over `irregular_whitespaces` and just call `ctx.diagnostic(NoIrregularWhitespaceDiagnostic(irregular_ whitespace))` and that's it!

if we don't check it'll not pass and all tests, but i have some doubts about the tests relevance, can i proceed without checks?

2024-01-04 02:27 UTC, Dunqing commented
> > I don't think we need to check irregular_whitespaces again. we can loop over `irregular_whitespaces` and just call `ctx.diagnostic(NoIrregularWhitespaceDiagnostic(irregular_ whitespace))` and that's it!
> 
> if we don't check it'll not pass and all tests, but i have some doubts about the tests relevance, can i proceed without checks?

I think we can comment out the failed test first. And then figure out how to fix it.

2024-01-04 03:55 UTC, Boshen commented
> I think we can comment out the failed test first. And then figure out how to fix it.

I Agree. It seems like most of the tests can be fixed by fixing the lexer, it's not saving all the irregular whitespaces.

2024-01-05 02:42 UTC, Dunqing approved these changes

2024-01-05 02:42 UTC, Boshen commented
Thank you!

(I removed the redundant `.clone()`.)

2024-01-05 02:47 UTC, merged