feat(linter): eslint: no-void
oxc-project/oxc pull request #2162
Opened 2024-01-24 16:57 UTC by eryue0220

Rule Detail: [link](https://github.com/eslint/eslint/blob/main/lib/rules/no-void.js)

2024-01-24 22:53 UTC, Dunqing requested changes
Thank you!

2024-01-24 22:53 UTC, Dunqing commented on crates/oxc_linter/src/snapshots/no_void.snap
> + 1 │ void 0
Shall we point the span to `void`?

2024-01-25 03:31 UTC, eryue0220 commented on crates/oxc_linter/src/snapshots/no_void.snap
> + 1 │ void 0
Done~

2024-01-25 04:00 UTC, Dunqing approved these changes

2024-01-25 04:40 UTC, merged