feat: add typescript-eslint rule array-type
oxc-project/oxc pull request #2292
Opened 2024-02-04 08:03 UTC by luhc228

Ref: https://github.com/oxc-project/oxc/issues/2180

Most test cases which from [eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/tests/rules/array-type.test.ts) pass, but some don't. At this time I could not figure out. I want to add more test cases after some time.

2024-02-04 21:58 UTC, camc314 reviewed
missing a snapshot file?

2024-02-05 05:17 UTC, Boshen requested changes

2024-02-05 05:17 UTC, Boshen commented on crates/oxc_linter/src/rules/typescript/array_type.rs
> +    Tester::new(ArrayType::NAME, pass, fail).expect_fix(fix).test();
need to call `test_and_snapshot`

2024-02-06 02:40 UTC, Boshen approved these changes
Thank you!

2024-02-06 02:53 UTC, luhc228 commented
clippy error must fixed before merging pr? @Boshen

2024-02-06 03:35 UTC, merged