feat(transformer/decorators): insert only one private in expression
oxc-project/oxc pull request #2486
Opened 2024-02-24 08:15 UTC by Dunqing

2024-02-24 08:16 UTC, Dunqing commented
Current dependencies on/for this PR:
* **#2486** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/2486?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/oxc-project/oxc/2486?utm_source=stack-comment).

2024-02-25 14:54 UTC, Boshen approved these changes

2024-02-25 14:54 UTC, Boshen commented
conflict?

2024-02-26 04:42 UTC, Boshen requested changes
conflict

2024-02-26 07:48 UTC, Boshen approved these changes

2024-02-26 07:48 UTC, merged