feat(linter): implement no-unused-labels
oxc-project/oxc pull request #282
Opened 2023-04-15 15:48 UTC by CarrotzRule123

Implement the Eslint rule no-unused-labels mentioned in https://github.com/Boshen/oxc/issues/123.

2023-04-15 16:00 UTC, Boshen requested changes

2023-04-16 05:59 UTC, CarrotzRule123 commented on crates/oxc_semantic/src/builder.rs
> +                    }
Fixed in 0157ef867492a2abaa413296b2c054c25d3935cc

2023-04-16 05:59 UTC, CarrotzRule123 commented on crates/oxc_semantic/src/node/mod.rs
> +        const UnusedLabel = 1 << 2;
Fixed in 0157ef867492a2abaa413296b2c054c25d3935cc

2023-04-16 06:01 UTC, CarrotzRule123 commented on crates/oxc_semantic/src/node/mod.rs
> +        const UnusedLabel = 1 << 2;
Would it be better to add a method such as `run_once` to the `Rule` trait instead of using `if AstKind::Root == node.get().kind()`?

2023-04-16 06:13 UTC, Boshen commented on crates/oxc_semantic/src/node/mod.rs
> +        const UnusedLabel = 1 << 2;
Yes, we should add a run_once in the next PR.

2023-04-16 13:10 UTC, Boshen approved these changes

2023-04-16 13:10 UTC, merged

2023-04-16 13:10 UTC, Boshen commented
Nice, Thank you!

2023-07-28 14:28 UTC, suica commented
Quite helpful, thanks!