refactor(diagnostic): 1 diagnostic
oxc-project/oxc pull request #3214
Opened 2024-05-09 08:07 UTC by Boshen

2024-05-09 14:47 UTC, Dunqing requested changes

2024-05-09 14:47 UTC, Dunqing commented on crates/oxc_diagnostics/src/lib.rs
> +        Some(self.severity.unwrap_or(Severity::Warning))
```suggestion
        self.severity
```

/// If `None`, reporters should treat this as [`Severity::Error`].

2024-05-09 15:15 UTC, elenakrittik commented
Would it be better to use miette's built-in [`MietteDiagnostic`](https://docs.rs/miette/latest/miette/struct.MietteDiagnostic.html) instead of a custom type? Or do you expect the cost of `String` allocations to be too high?

2024-05-09 16:31 UTC, Boshen commented
> Would it be better to use miette's built-in [`MietteDiagnostic`](https://docs.rs/miette/latest/miette/struct.MietteDiagnostic.html) instead of a custom type? Or do you expect the cost of `String` allocations to be too high?

How did I miss this after all these time (2 years) ...

2024-05-10 16:16 UTC, Boshen commented
> Would it be better to use miette's built-in [`MietteDiagnostic`](https://docs.rs/miette/latest/miette/struct.MietteDiagnostic.html) instead of a custom type? Or do you expect the cost of `String` allocations to be too high?

Haha, rust complained, back to creating our own struct

```
error: the `Err`-variant returned from this function is very large
   --> crates/oxc_parser/src/lib.rs:338:36
    |
338 |     fn parse_program(&mut self) -> Result<Program<'a>> {
    |                                    ^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 128 bytes
```

2024-05-10 16:16 UTC, Boshen commented
> Would it be better to use miette's built-in [`MietteDiagnostic`](https://docs.rs/miette/latest/miette/struct.MietteDiagnostic.html) instead of a custom type? Or do you expect the cost of `String` allocations to be too high?

Haha, rust complained, back to creating our own struct

```
error: the `Err`-variant returned from this function is very large
   --> crates/oxc_parser/src/lib.rs:338:36
    |
338 |     fn parse_program(&mut self) -> Result<Program<'a>> {
    |                                    ^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 128 bytes
```

2024-05-10 17:26 UTC, Boshen commented
Binary size for `cargo build --release --example parser` shrank from 1.0M to 958K. Big win!

2024-05-11 00:42 UTC, Dunqing commented
Very much looking forward to shrinking in the linter!

2024-05-11 00:42 UTC, Dunqing approved these changes

2024-05-11 05:00 UTC, merged