feat(linter/eslint): Implement no-useless-concat
oxc-project/oxc pull request #3363
Opened 2024-05-20 13:10 UTC by jelly

Rule Detail:
[link](https://eslint.org/docs/latest/rules/no-useless-concat)

---

I haven't implemented one condition with the multiline string test case and honestly I don't really understand why it is allowed? And also not sure how I would implement that in oxlint.

Another issue is that maybe the output isn't great, the underlining matches the whole BinaryExpression, for example:
```
+   ╭─[no_useless_concat.tsx:1:1]
+ 1 │ foo + `a` + `b`
+   · ───────────────
```

So maybe instead the diagnostic should get two spans passed, for each Expression::StringLiteral or Expression::TemplateLiteral, that would also allow the help text to show that it can be written as `"ab"`.

But an automatic fixxer would be more helpful I reckon :)

2024-05-20 14:38 UTC, Boshen commented
> I haven't implemented one condition with the multiline string test case and honestly I don't really understand why it is allowed?

People often write paragraphs with this style (from some random tutorial):

```javascript
let learnCoding = 'How to start learning web development?' +
' - Learn HTML' +
' - Learn CSS' +
' - Learn JavaScript' +
' Use freeCodeCamp to learn all the above and much, much more!'
```

To pass this test, you need to scan for newlines between these two expressions I think.

2024-05-20 14:40 UTC, Boshen commented
> Another issue is that maybe the output isn't great, the underlining matches the whole BinaryExpression

We try to minimize the span, so maybe from the start of the first string to the last?

```
+   ╭─[no_useless_concat.tsx:1:1]
+ 1 │ foo + `a` + `b`
+   ·       ────────
```

2024-05-20 14:46 UTC, Boshen approved these changes

2024-05-20 14:46 UTC, Boshen commented on crates/oxc_linter/src/rules/eslint/no_useless_concat.rs
> +    suspicious
This rule produces useless code, which fits in our category of `correctness`. I'll test this in real codebases and see if I can change this to `correctness`.

Or if you wanna try out yourself: https://github.com/oxc-project/oxlint-ecosystem-ci

2024-05-22 04:45 UTC, Boshen requested changes
@jelly would you like to address the questions?

2024-05-22 06:53 UTC, jelly commented
> @jelly would you like to address the questions?

Yes, will do! Likely later this week. I opened the other PR because it was close to the finish line and things finally clicked :)

2024-05-25 17:41 UTC, Boshen commented on crates/oxc_linter/src/rules/eslint/no_useless_concat.rs
> +    suspicious
It seems like people love to concatenate strings ...

2024-05-25 17:42 UTC, Boshen approved these changes
I ported the eslint source code 😅

2024-05-25 17:52 UTC, merged