fix(transformer): output empty file for TS definition files
oxc-project/oxc pull request #3500
Opened 2024-06-01 16:22 UTC by overlookmotel

2024-06-01 16:23 UTC, overlookmotel commented
* **#3500** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/3500?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-01 16:31 UTC, overlookmotel commented
@Boshen Can I just double-check with you this is correct? Dunqing thinks so.

2024-06-03 04:16 UTC, Boshen requested changes
Need a test for this to catch regressions.

2024-06-03 07:31 UTC, Dunqing commented
You can add tests in `oxc/tasks/transform_conformance/tests/babel-plugin-transform-typescript/test/fixtures`

2024-06-03 12:24 UTC, Boshen approved these changes

2024-06-03 12:25 UTC, merged