feat(ast, ast_macros): apply stable_repr to all `#[ast]` items.
oxc-project/oxc pull request #4373
Opened 2024-07-20 10:35 UTC by rzvxa

2024-07-20 10:35 UTC, rzvxa commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4373?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#4373** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4373?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#4371** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4371?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4309** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4309?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#4289** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/4289?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rzvxa and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-22 21:04 UTC, overlookmotel requested changes

2024-07-22 21:04 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
>  pub fn ast(_args: TokenStream, input: TokenStream) -> TokenStream {
Doc comment above this function needs updating to reflect that this is a real macro now and adds `#[repr]` attribute to types.

2024-07-22 21:04 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
> +fn enum_repr(enum_: &syn::ItemEnum) -> TokenStream2 {
Please add doc comment on this function clarifying when it's `#[repr(C)]` and when `#[repr(C, u8)]`.

2024-07-22 21:10 UTC, overlookmotel commented
Aside from comments above, this looks good.

But... I suggest we hold off merging until rest of the stack is complete. With just this PR, the types' memory layouts are not optimal, and you can see it a bit on benchmarks. Let's wait until macro+codegen rearranges the fields so they end up in same order as they were before `#[repr(C)]` was applied.

2024-08-01 22:52 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
> +/// Otherwise it would return `#[repr(C)]`.
```suggestion
/// Otherwise it would return `#[repr(u8)]`.
```

2024-08-01 22:52 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
> +        quote!(#[repr(C)])
`#[repr(u8)]` is what we want for fieldless enums.

```suggestion
        quote!(#[repr(u8)])
```

2024-08-01 22:52 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
> +        syn::Item::Struct(_) => TokenStream2::default(),
```suggestion
        // In future, we'll add `#[repr(C)]` to structs, but at present this is disabled
        syn::Item::Struct(_) => TokenStream2::default(),
```

2024-08-01 22:52 UTC, overlookmotel commented on crates/oxc_ast_macros/src/lib.rs
> +/// * Prepend `#[repr(C)]` to unit enums
```suggestion
/// * Prepend `#[repr(C, u8)]` to fieldful enums e.g. `enum E { X: u32, Y: u8 }`
/// * Prepend `#[repr(u8)]` to unit (fieldless) enums e.g. `enum E { X, Y, Z, }`
```

2024-08-01 23:09 UTC, overlookmotel commented
@rzvxa Aside from comments above, and resolving conflicts, I think this PR + 3 more above it in this stack are ready to merge.

2024-08-02 00:06 UTC, overlookmotel approved these changes

2024-08-02 00:13 UTC, merged