feat(linter): eslint-plugin-vitest/no-import-node-test
oxc-project/oxc pull request #4440
Opened 2024-07-24 03:16 UTC by eryue0220

support [eslint-plugin-vitest/no-import-node-test](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/no-import-node-test.md)

2024-07-24 05:50 UTC, mysteryven approved these changes

2024-07-24 05:55 UTC, mysteryven commented on crates/oxc_linter/src/rules/vitest/no_import_node_test.rs
> +        };
Let's try use [module record](https://github.com/oxc-project/oxc/blob/a207923af1b87953e89ecbf0fe272cf7134b71ef/crates/oxc_syntax/src/module_record.rs#L17)

2024-07-24 05:56 UTC, mysteryven requested changes
Let's try module record to see if it can improve our performance👀

To run benchmark for vitest rule, we also need modify: https://github.com/oxc-project/oxc/blob/7a75e0f8a77006ef32fa0db45a329d961e70bdf3/tasks/benchmark/benches/linter.rs#L44-L51

2024-07-24 12:53 UTC, eryue0220 commented
> Let's try module record to see if it can improve our performance👀
> 
> To run benchmark for vitest rule, we also need to modify:
> 
> https://github.com/oxc-project/oxc/blob/7a75e0f8a77006ef32fa0db45a329d961e70bdf3/tasks/benchmark/benches/linter.rs#L44-L51

still the same problem. :(

2024-07-24 14:27 UTC, mysteryven commented
> still the same problem. :(

We can try to use module record. e.g. 

1. https://github.com/oxc-project/oxc/blob/7a75e0f8a77006ef32fa0db45a329d961e70bdf3/crates/oxc_linter/src/rules/import/no_self_import.rs#L30-L46
2. https://github.com/oxc-project/oxc/blob/7a75e0f8a77006ef32fa0db45a329d961e70bdf3/crates/oxc_linter/src/frameworks.rs#L83-L85

2024-07-29 02:01 UTC, eryue0220 commented
Thanks, it works!!

2024-07-29 05:53 UTC, mysteryven approved these changes
Nice!

2024-07-29 05:53 UTC, merged