feat(linter): Implement eslint(getter-return)
oxc-project/oxc pull request #449
Opened 2023-06-15 14:52 UTC by Maneren

2023-06-15 15:01 UTC, Boshen requested changes

2023-06-15 15:15 UTC, Boshen requested changes

2023-06-15 15:15 UTC, Boshen commented on crates/oxc_linter/src/rules/getter_return.rs
> +                        let span = Span {
nit: use `Span::new`

2023-06-15 15:39 UTC, Boshen commented
`cargo test && cargo insta accept`

2023-06-15 15:46 UTC, Maneren commented
Yh, I went out and am only on a phone. Will fix it when I get back home in a few hours.

2023-06-16 02:09 UTC, merged

2023-06-16 02:10 UTC, Boshen commented
I would not have implemented better than this, thank you so much!