feat(minifier): fold string string comparison
oxc-project/oxc pull request #471
Opened 2023-06-23 06:07 UTC by mysteryven

2023-06-24 13:46 UTC, Boshen commented on crates/oxc_hir/src/hir_util.rs
> +fn get_string_value(expr: &Expression) -> Option<String> {
It is better to return `&str` instead of an allocated `String`

2023-06-24 13:49 UTC, Boshen requested changes

2023-06-24 13:49 UTC, Boshen commented on crates/oxc_hir/src/hir_util.rs
> +fn get_string_value(expr: &Expression) -> Option<String> {
It is better to return &str instead of an allocated String

2023-06-24 13:49 UTC, Boshen commented on crates/oxc_hir/src/hir_util.rs
> +fn get_string_value(expr: &Expression) -> Option<String> {
It seems you need to return allocated string in some cases? Try `get_string_value<'a>(expr: &'a Expression) -> Option<Cow<'a, str>>`

2023-06-25 15:58 UTC, Boshen approved these changes

2023-06-25 15:58 UTC, Boshen commented on crates/oxc_hir/src/hir_util.rs
> +        Expression::ObjectExpression(_) => Some("[object Object]".to_string().into()),
Does Cow::owned or Cow::borrowed work? This is static so it has a longer lifetime

2023-06-26 14:02 UTC, mysteryven commented
I have refactored it. Could you please take a look?

2023-06-26 14:37 UTC, merged