fix(transformer/react): don't transform if the variable does not have a value reference
oxc-project/oxc pull request #5528
Opened 2024-09-06 08:57 UTC by Dunqing

2024-09-06 08:57 UTC, Dunqing commented
* **#5528** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/5528?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Dunqing and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-06 09:20 UTC, Boshen requested changes
Add a fail test.

2024-09-09 01:23 UTC, Boshen commented
Needs a quick rebase.

2024-09-11 07:07 UTC, Boshen approved these changes

2024-09-11 07:16 UTC, merged