fix(semantic): correctly resolve binding for return type of functions
oxc-project/oxc pull request #6388
Opened 2024-10-09 16:00 UTC by overlookmotel

2024-10-09 16:01 UTC, overlookmotel commented
* **#6388** <a href="https://app.graphite.dev/github/pr/oxc-project/oxc/6388?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @overlookmotel and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-09 16:09 UTC, overlookmotel commented
...or at least I *think* it's a fix. @Dunqing could you please help me with this one?

Questions:

1. There are various TS types which contain `FormalParameters`:

* `TSCallSignatureDeclaration`
* `TSMethodSignature`
* `TSConstructSignatureDeclaration`
* `TSFunctionType`
* `TSConstructorType`

None of these function types have a body, so I assume we're OK to skip the extra call to `resolve_references_for_current_scope` for them, right?

2. Is the `func.params.kind != FormalParameterKind::Signature` check required for `Function` and `ArrowFunctionExpression`? Or can their params never have `kind: FormalParameterKind::Signature` anyway?

3. How/where would I add tests for this?

2024-10-10 03:58 UTC, Dunqing commented
> Questions:
> 
> 1. There are various TS types which contain `FormalParameters`:
> 
> * `TSCallSignatureDeclaration`
> * `TSMethodSignature`
> * `TSConstructSignatureDeclaration`
> * `TSFunctionType`
> * `TSConstructorType`
> 
> None of these function types have a body, so I assume we're OK to skip the extra call to `resolve_references_for_current_scope` for them, right?
>
 
Right

> 2. Is the `func.params.kind != FormalParameterKind::Signature` check required for `Function` and `ArrowFunctionExpression`? Or can their params never have `kind: FormalParameterKind::Signature` anyway?

Skipping `func.params.kind != FormalParameterKind::Signature` is ok

> 3. How/where would I add tests for this?

￼I think as long as there are no test failures, it’s fine, so we don’t need to add tests for it.

2024-10-10 04:04 UTC, Dunqing requested changes

2024-10-10 04:04 UTC, Dunqing commented on crates/oxc_semantic/src/builder.rs
> +        if expr.params.kind != FormalParameterKind::Signature && expr.params.has_parameter() {
If I remember correctly, the `FormalParameterKind` of `ArrowFunctionExpression` and `Function` never going to be  `FormalParameterKind::Signature`, so if you want to call `resolve_references_for_current_scope` here, I think you don't need to check anymore.

2024-10-10 10:13 UTC, overlookmotel commented
> > 2. Is the `func.params.kind != FormalParameterKind::Signature` check required for `Function` and `ArrowFunctionExpression`? Or can their params never have `kind: FormalParameterKind::Signature` anyway?
> 
> Skipping `func.params.kind != FormalParameterKind::Signature` is ok

Great. I've removed that.

> > 3. How/where would I add tests for this?
> 
> ￼I think as long as there are no test failures, it’s fine, so we don’t need to add tests for it.

But #6387 was a bug, and this PR fixes it. So there should have been a test failing before, but there wasn't. So I think we should add one. I just don't know where to put it. Can you point me in right direction please?

2024-10-10 13:52 UTC, Dunqing commented
> But #6387 was a bug, and this PR fixes it. So there should have been a test failing before, but there wasn't. So I think we should add one. I just don't know where to put it. Can you point me in right direction please?

Oh, sorry, I didn't notice that. We have two ways to write semantic tests:

1. The snapshot-based tests, you can add a test [here](https://github.com/oxc-project/oxc/blob/93575cd09e626a783c780d244996a447099e5782/crates/oxc_semantic/tests/fixtures/oxc), and then run https://github.com/oxc-project/oxc/blob/c822b48d4f7eedf4db803d158cfe7bcde24c25ea/crates/oxc_semantic/tests/main.rs#L158-L172

2. The integration test, you can add [here](https://github.com/oxc-project/oxc/blob/c822b48d4f7eedf4db803d158cfe7bcde24c25ea/crates/oxc_semantic/tests/integration/symbols.rs#L493)

Either two ways are ok. I prefer the first way because I can see what scopes/symbols have in the test code

2024-11-25 11:03 UTC, Dunqing commented
Let me add tests to it

2024-11-26 15:38 UTC, Dunqing approved these changes

2024-11-26 15:41 UTC, Boshen commented
### Merge activity

* **Nov 26, 10:41 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

2024-11-26 15:53 UTC, merged

2024-11-26 16:05 UTC, overlookmotel commented
Thank you very much for cleaning up the mess I left!