impl ASTNode for VariableDeclarationAST
oxc-project/oxc pull request #639
Opened 2023-07-26 19:05 UTC by u9g

2023-07-26 19:34 UTC, obi1kenobi approved these changes
This seems fine, but probably worth proactively searching for other possible mistakes like this as well.

2023-07-26 19:34 UTC, obi1kenobi commented on crates/oxc_query/src/schema.graphql
> -  entire_span: Span!
The structure here makes me think this type was intended to implement `ASTNode` and `HasSpan` previously, but did not.

Could you proactively look for other places in the schema where such a bug might have happened?

2023-07-27 01:47 UTC, Boshen approved these changes

2023-07-27 01:47 UTC, Boshen requested changes, later dismissed
A small merge conflict.

2023-07-27 03:30 UTC, Boshen approved these changes

2023-07-27 03:30 UTC, merged