fix(ast): Fix StaticMemberExpression.get_first_object function
oxc-project/oxc pull request #6969
Opened 2024-10-27 22:32 UTC by tbashiyy

# Why
`get_fist_object` does not return expected expression.

For example, in case of `foo.bar.a`.

**Expected**
```
{
  "type": "Identifier",
  "start": 0,
  "end": 3,
  "name": "foo"
}
```

**Actual**
```
{
   "type":"StaticMemberExpression",
   "start":0,
   "end":7,
   "object":{
      "type":"Identifier",
      "start":0,
      "end":3,
      "name":"foo"
   },
   "property":{
      "type":"Identifier",
      "start":4,
      "end":7,
      "name":"bar"
   },
   "optional":false
}
```

2024-10-30 03:20 UTC, Boshen commented
@Dunqing can you check the ID failures?

2024-10-31 08:03 UTC, Dunqing requested changes, later dismissed

2024-11-01 00:48 UTC, tbashiyy commented on crates/oxc_ast/src/ast_impl/js.rs
>              }
Thanks!
fixed 9ae5f1922d687c19deb726d3fa7463eea2358494

2024-11-01 03:27 UTC, Boshen commented
Conformance still failing @Dunqing

2024-11-01 04:19 UTC, Dunqing approved these changes
I have checked in [TypeScript](https://www.typescriptlang.org/play/?target=99&isolatedDeclarations=true&noCheck=true&ssl=7&ssc=1&pln=8&pc=1#code/FAUwHgDg9gTgLgAjgTwiBBBBBeBBvYBBAbQFsBLAZ0vIDsBzAXQC4FaBXUgIxBgBpCJWpQB0FanSasO3XgKLEIMEJRC04AOVEBDFm049+g4gGVk3KABsR5OL21xYemYfkl6lqF22WAKgAsqETMLa0cTOBhJX20pfVkjBQAKDy8fAKCQrisAShF2YQBjKAhtLksVZwM5Yx9ybRoGG0oAYShaQocTJRBtABMyiqqEt2IARmHXYwAiACZpyZrk8Ub6WZzFxJIAWQd-ERhtWj6oUiSchAA+BAAGEQBWBAB+BGmAMzHphFZ3+c2BAC+AG5gEA), the snapshot changes is correct. You even fixed an IsolatedDeclarations bug! Thanks!

2024-11-01 04:28 UTC, merged