refactor(semantic): infer ReferenceFlags from Visit methods
oxc-project/oxc pull request #7388
Opened 2024-11-21 08:20 UTC by Dunqing

2024-11-21 09:03 UTC, Dunqing commented
I prefer to fix transformer-related semantic errors in follow-up PR, but if you think should be fixed in this PR I am okay

2024-11-21 09:07 UTC, Boshen requested changes
Can you add the test case to no-const-assign?

```
const FOO = 1;

({
  files = FOO,
} = arg1);
```

2024-11-21 09:11 UTC, Boshen approved these changes

2024-11-21 09:11 UTC, Boshen commented on crates/oxc_semantic/src/builder.rs
> +        // Only the operator is not an `=` operator, the left-hand side is both read and write.
```suggestion
        // Only when the operator is not an `=` operator, the left-hand side is both read and write.
```

2024-11-21 09:12 UTC, Boshen commented
Can 

> Can you add the test case to no-const-assign?
> 
> ```
> const FOO = 1;
> 
> ({
>   files = FOO,
> } = arg1);
> ```

Can you add all the assignment cases to no object assign?

2024-11-21 09:17 UTC, Dunqing commented
> Can you add the test case to no-const-assign?
> 
> ```
> const FOO = 1;
> 
> ({
>   files = FOO,
> } = arg1);
> ```

Added

> Can you add all the assignment cases to no object assign?

I have already added a lot of assignment-related tests in semantic.

2024-11-22 06:05 UTC, Boshen commented
### Merge activity

* **Nov 22, 1:05 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

2024-11-22 06:16 UTC, merged

2024-11-24 14:52 UTC, overlookmotel commented
@Dunqing Is `x` in `x++` now `Read | Write`? I can't see tests for this (if I remember right, previously it was `Write` only which is incorrect).

2024-11-26 15:35 UTC, Dunqing commented
> @Dunqing Is `x` in `x++` now `Read | Write`? I can't see tests for this (if I remember right, previously it was `Write` only which is incorrect).

Yes, you are right. The test is added in https://app.graphite.dev/github/pr/oxc-project/oxc/7495.