fix(oxc_transformer): correct generate `ThisExpr` and `import.meta` in jsx pragma
oxc-project/oxc pull request #7553
Opened 2024-11-30 10:38 UTC by IWANABETHATGUY

2024-12-02 03:04 UTC, Boshen commented
@overlookmotel need your review.

2024-12-02 14:42 UTC, overlookmotel requested changes
Sorry to say I see problems.

Also, could you please add a test for `import.meta`?

We can make this more performant by changing `Pragma` into an enum, to avoid string comparisons on every call to `create_expression`. Something like:

```rs
enum Pragma<'a> {
  /// `createElement`
  Single(Atom<'a>),
  /// `React.createElement`
  Double(Atom<'a>, Atom<'a>),
  /// `foo.bar.qux`
  Many(Vec<Atom<'a>>),
  /// `this`, `this.foo`, `this.foo.bar.qux`
  This(Vec<Atom<'a>>),
  /// `import.meta`, `import.meta.foo`, `import.meta.foo.bar.qux`
  ImportMeta(Vec<Atom<'a>>),
}
```

In practice, it's going to always be `Single` or `Double`. All the others are edge cases.

But we can do that optimization in a follow-up.

2024-12-03 12:42 UTC, overlookmotel commented on crates/oxc_transformer/src/jsx/jsx_impl.rs
> +            _ => panic!("Expected ThisExpression"),
```suggestion
            _ => panic!("Expected MetaProperty"),
```

2024-12-03 12:44 UTC, overlookmotel commented on crates/oxc_transformer/src/jsx/jsx_impl.rs
> +            _ => panic!("Expected ThisExpression"),
Or how about:

```rs
assert!(matches!(member_expr.object(), Expression::MetaProperty(_)));
```

2024-12-03 13:53 UTC, overlookmotel approved these changes
Thanks for adding the tests.

I've pushed a couple more commits:

1. Get rid of the `Box`es in `create_arbitrary_length_member_expr_or_ident`. They didn't appear to add anything.
2. Tweak the tests to make them more explicit.

2024-12-03 13:53 UTC, overlookmotel commented
### Merge activity

* **Dec 3, 8:53 AM EST**: The merge label '0-merge' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=oxc-project&repo=oxc) once it meets the requirements.

2024-12-03 13:59 UTC, merged