feat(linter): create the import/order rule
oxc-project/oxc pull request #7903
Opened 2024-12-14 23:05 UTC by Spoutnik97

all cases are not covered bu the architecture is setup

2024-12-15 04:21 UTC, Boshen requested changes
It seems like this is for https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md and not https://eslint.org/docs/latest/rules/sort-imports

Biome also has a separate import sorting step https://biomejs.dev/analyzer/import-sorting/

I wonder what the differences are.

2024-12-15 20:37 UTC, Sysix commented
@Spoutnik97 thanks for the work 👍 

It feels like you are going to the toruble of making your own file with tests. Please have a look how to setup a new rule:
https://oxc.rs/docs/contribute/linter/adding-rules.html

The `just` commands looks to be outdated🙃 . The listed commands can also be found here:
https://github.com/oxc-project/oxc/blob/main/justfile#L159-L199

2024-12-15 22:36 UTC, Spoutnik97 commented
@Sysix oh great! Indeed I didn't know this refreshed list

2024-12-16 20:53 UTC, Spoutnik97 commented
> https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md

@Boshen yes indeed, this is for [this rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)

It seems that differences are you cannot customize the order/groups with biomejs

2024-12-16 22:24 UTC, camc314 commented on crates/oxc_linter/src/snapshots/eslint_order.snap
i do'nt think this snap should be committed

2024-12-16 22:25 UTC, camc314 commented
We've also got https://github.com/oxc-project/oxc/discussions/7197 which we were considering implementing

2024-12-16 23:15 UTC, Spoutnik97 commented
I just improved the rule by covering more use cases. Indeed, it would be better to don't have duplicate rule effects
I fixed tests and move to the right folders

2024-12-25 14:47 UTC, Spoutnik97 commented
Performances issues are fixed. 
All checks passed

2025-01-06 22:45 UTC, Spoutnik97 commented on crates/oxc_linter/src/snapshots/eslint_order.snap
Yes, I forgot it

2025-01-09 03:32 UTC, Sysix commented
Hello ✋ 
we updated the tests for rules in this PR: https://github.com/oxc-project/oxc/pull/8353
Could you please rebase/merge your PR with main foir the needed changes? 🙌?

2025-01-09 21:45 UTC, Spoutnik97 commented
Hi @Sysix !
It's done ✅

2025-01-13 20:53 UTC, Spoutnik97 commented
Hi @Sysix and @Boshen !

How could I help you to accelerate the merge of this PR?

It's one of the rule I need to fully migrate to oxlint.

I will improve my ci from 56sec to 9 sec ! (x5 per day)

2025-01-15 22:03 UTC, Sysix commented
Hello @Spoutnik97 

I do not feel comfortable when the test generation from `just new-import-rule` is failing :/ 
The rules have more options and more test cases too pass. I do not expect it pass it 100% in this PR.
Still I would like to have the test cases in the code, ready to be enabled.

And your configuration file test cases are wrong. You need to pass a js array like the auto generated tests here:
https://github.com/oxc-project/oxc/blob/52bd0b1004b376c76cb0d808b2cc45930a4bb3d0/crates/oxc_linter/src/rules/eslint/new_cap.rs#L694

PS: I am currently not the person to request :) I just look around and try to help where I can

2025-03-13 06:35 UTC, huangtiandi1999 commented
Hello @Spoutnik97 
Is this job going on? this rule is very useful to many developers, i will be exciting if this PR is merged (👍

2025-03-13 06:38 UTC, Spoutnik97 commented
Yes it is , but I don't have a lot of time the last weeks.

I am reshaping the rule according to the official eslint tests I writed manually.

My code pass the main tests, but there is still some work to be done

2025-03-24 01:33 UTC, Boshen commented
Converted to draft. Please let us know when PR is ready for review.

2025-04-25 22:12 UTC, Spoutnik97 commented
@Boshen a first version is ready to review. Not all config is implemented, but dozens of eslint tests pass, so I think it could be a good start for the next steps. 
let me know if it seems right for you

2025-06-03 19:59 UTC, Spoutnik97 commented
@camc314  maybe ?

2025-06-24 13:10 UTC, vladimir-kuba commented
Hi, the PR sims to be intact for 3 weeks. Are there any plans to move it from draft to open PR in a short future? Is any help required? @Spoutnik97

2025-06-26 19:40 UTC, Spoutnik97 commented
@vladimir-kuba I did the job and I am waiting for a reviewer.
I don't know if I have the permissions to change the draft label

2025-06-26 21:18 UTC, Sysix commented
@Spoutnik97 can you resolve the conflicts? :)

2025-06-29 14:26 UTC, vladimir-kuba commented
@Spoutnik97 thanks for the reply! I see no [settings] implemented in the PR. even though the [import/internal-regex] and [import/external-module-folders] are mentioned in the [How Imports Are Grouped] docs.

Is it reasonable to implement the settings in the PR or in a separate one?

[settings]: https://github.com/import-js/eslint-plugin-import/blob/main/README.md#settings
[import/internal-regex]: https://github.com/import-js/eslint-plugin-import/blob/main/README.md#importinternal-regex
[import/external-module-folders]: https://github.com/import-js/eslint-plugin-import/blob/main/README.md#importexternal-module-folders
[How Imports Are Grouped]: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#how-imports-are-grouped

2025-07-14 18:28 UTC, Spoutnik97 commented
@vladimir-kuba I'm not sure about what you mean. In the crates/oxc_linter/src/rules/import/order.rs file, there is a configuration parser to get the specified settings for this rule

2025-07-21 21:38 UTC, Spoutnik97 commented
@Sysix done ✅ !

2025-07-22 07:28 UTC, Spoutnik97 commented
@Sysix or @camc314 I don't understand why the Test Linux CI failed on tests I didn't modified. Why does it failed on linux and now macos or windows ?

2025-08-26 02:42 UTC, Boshen commented
We address import order properly in the formatter.

2025-08-26 02:42 UTC, closed without merging